services:
  postgres:
    image: "postgres:16.3-alpine3.20"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - POSTGRES_PASSWORD=p3r$is+ENc3
      # - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      # - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=super-secret-key
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_PORT=5432
